dirs = [
 # '/Volumes/media/audiobooks/Daphne du Maurier/Rebecca',
 # '/Volumes/media/audiobooks/P.G. Wodehouse/Carry On, Jeeves',
 # '/Volumes/media/audiobooks/P.G. Wodehouse/The Code of the Woosters',
 # '/Volumes/media/audiobooks/P.G. Wodehouse/The Inimitable Jeeves',
 # '/Volumes/media/audiobooks/P.G. Wodehouse/My Man Jeeves',
 # '/Volumes/media/audiobooks/P.G. Wodehouse/Carry On, Jeevesx',
 '/Volumes/media/audiobooks/Mira Grant/Feedback',
 '/Volumes/media/audiobooks/Mira Grant/Parasite',
 '/Volumes/media/audiobooks/Mira Grant/Symbiont',
 '/Volumes/media/audiobooks/Mira Grant/Feed',
 '/Volumes/media/audiobooks/Mira Grant/Into the Drowning Deep',
 '/Volumes/media/audiobooks/Mira Grant/Blackout',
 '/Volumes/media/audiobooks/Mira Grant/Rise',
 '/Volumes/media/audiobooks/Mira Grant/Deadline',
 '/Volumes/media/audiobooks/Mira Grant/Chimera',
 '/Volumes/media/audiobooks/Grace Burrowes/A Rogue of Her Own',
 '/Volumes/media/audiobooks/Grace Burrowes/The Trouble With Dukes',
 '/Volumes/media/audiobooks/Grace Burrowes/Too Scot to Handle',
 '/Volumes/media/audiobooks/Grace Burrowes/No Other Duke Will Do',
 '/Volumes/media/audiobooks/Julia Quinn/Ten Things I Love About You',
 '/Volumes/media/audiobooks/Julia Quinn/What Happens in London',
 '/Volumes/media/audiobooks/Julia Quinn/The Secrets of Sir Richard Kenworthy',
 '/Volumes/media/audiobooks/Julia Quinn/Just Like Heaven',
 '/Volumes/media/audiobooks/Julia Quinn/The Lady Most Likely',
 '/Volumes/media/audiobooks/Julia Quinn/Because of Miss Bridgerton',
 '/Volumes/media/audiobooks/Julia Quinn/The Sum of All Kisses',
 '/Volumes/media/audiobooks/Julia Quinn/The Girl with the Make-Believe Husband',
 '/Volumes/media/audiobooks/Julia Quinn/A Night Like This',
 '/Volumes/media/audiobooks/Barbara Kingsolver/Prodigal Summer',
 '/Volumes/media/audiobooks/Barbara Kingsolver/Animal Dreams',
 '/Volumes/media/audiobooks/Barbara Kingsolver/Small Wonder',
 '/Volumes/media/audiobooks/Barbara Kingsolver/Flight Behavior',
 '/Volumes/media/audiobooks/Barbara Kingsolver/Animal, Vegetable, Miracle',
 '/Volumes/media/audiobooks/Barbara Kingsolver/Pigs in Heaven',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 40 - Raising Steam',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 33 - Going Postal',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 03 - Equal Rites',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 36 - Making Money',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 01 - The Colour of Magic',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 22 - The Last Continent',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 10 - Moving Pictures',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 11 - Reaper Man',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 08 - Guards Guards',
 '/Volumes/media/audiobooks/Terry Pratchett/Nation',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 16 - Soul Music',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 04 - Mort',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 21 - Jingo',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 35 - Wintersmith',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 38 - I Shall Wear Midnight',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 17 - Interesting Times',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 24 - The Fifth Elephant',
 "/Volumes/media/audiobooks/Terry Pratchett/Discworld 41 - The Shepherd's Crown",
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 30 - The Wee Free Men',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 06 - Wyrd Sisters',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 14 - Lords and Ladies',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 23 - Carpe Jugulum',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 07 - Pyramids',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 28 - Amazing Maurice',
 '/Volumes/media/audiobooks/Terry Pratchett/A Blink of the Screen',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 05 - Sourcery',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 37 - Unseen Academicals',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 27 - The Last Hero',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 13 - Small Gods',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 39 - Snuff',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 29 - Night Watch',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 15 - Men at Arms',
 "/Volumes/media/audiobooks/Terry Pratchett/Darwin's Watch",
 '/Volumes/media/audiobooks/Terry Pratchett/Covers',
 "/Volumes/media/audiobooks/Terry Pratchett/The Witch's Vacuum Cleaner and Other Stories",
 '/Volumes/media/audiobooks/Terry Pratchett/The Long Mars',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 02 - The Light Fantastic',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 20 - Hogfather',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 31 - Monstrous Regiment',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 32 - A Hat Full of Sky',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 25 - The Truth',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 34 - Thud',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 12 - Witches Abroad',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 09 - Eric',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 19 - Feet Of Clay',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 26 - Thief of Time',
 '/Volumes/media/audiobooks/Terry Pratchett/Discworld 18 - Maskerade',
 '/Volumes/media/audiobooks/Sarah Gailey/Taste of Marrow',
 '/Volumes/media/audiobooks/Sarah Gailey/River of Teeth',
 '/Volumes/media/audiobooks/Nora Roberts/Divine Evil',
 '/Volumes/media/audiobooks/Ilona Andrews/Magic Bites',
 '/Volumes/media/audiobooks/Ilona Andrews/Burn for Me',
 '/Volumes/media/audiobooks/Ilona Andrews/White Hot',
 '/Volumes/media/audiobooks/Tamora Pierce/Tempests and Slaughter',
 '/Volumes/media/audiobooks/Ursula Vernon',
 '/Volumes/media/audiobooks/Sophie Kinsella/Can You Keep a Secret?',
 '/Volumes/media/audiobooks/Sophie Kinsella/Surprise Me',
 '/Volumes/media/audiobooks/Sophie Kinsella/Remember Me',
 '/Volumes/media/audiobooks/Sophie Kinsella/My Not So Perfect Life',
 '/Volumes/media/audiobooks/Kate Elliott/Court of Fives',
 '/Volumes/media/audiobooks/Chelsea Sedoti/The Hundred Lies of Lizzie Lovett',
 '/Volumes/media/audiobooks/Jeff VanderMeer/Borne',
 '/Volumes/media/audiobooks/Jim Butcher/Furies of Calderon',
 '/Volumes/media/audiobooks/Jim Butcher/Death Masks',
 '/Volumes/media/audiobooks/David Mitchell/Cloud Atlas',
 '/Volumes/media/audiobooks/Courtney Milan',
 '/Volumes/media/audiobooks/Kit Rocha/Deacon',
 '/Volumes/media/audiobooks/Kit Rocha/Beyond Pain',
 '/Volumes/media/audiobooks/Kit Rocha/Ashwin',
 '/Volumes/media/audiobooks/Jennifer Crusie/The Cinderella Deal',
 '/Volumes/media/audiobooks/N. K. Jemisin/The Obelisk Gate',
 '/Volumes/media/audiobooks/N. K. Jemisin/The Stone Sky',
 '/Volumes/media/audiobooks/Nancy Springer/The Case of the Bizarre Bouquets',
 '/Volumes/media/audiobooks/Elizabeth Boyle/The Knave of Hearts',
 '/Volumes/media/audiobooks/Elizabeth Boyle/The Viscount Who Lived Down the Lane',
 '/Volumes/media/audiobooks/Elizabeth Boyle/And the Miss Ran Away with the Rake',
 '/Volumes/media/audiobooks/Elizabeth Boyle/If Wishes Were Earls',
 '/Volumes/media/audiobooks/Elizabeth Boyle/Along Came a Duke',
 '/Volumes/media/audiobooks/Elizabeth Boyle/Six Impossible Things',
 '/Volumes/media/audiobooks/Joseph Fink/Welcome to Night Vale',
 '/Volumes/media/audiobooks/Peter S. Beagle/In Calabria',
 '/Volumes/media/audiobooks/Rachel Joyce/The Unlikely Pilgrimage of Harold Fry',
 '/Volumes/media/audiobooks/Alyssa Cole/A Princess in Theory',
 '/Volumes/media/audiobooks/Alyssa Cole/A Duke by Default',
 '/Volumes/media/audiobooks/Sabrina Jeffries/To Wed a Wild Lord',
 '/Volumes/media/audiobooks/Seanan McGuire/Wayward Children #1 - Every Heart a Doorway',
 '/Volumes/media/audiobooks/Seanan McGuire/Dusk or Dark or Dawn or Day',
 '/Volumes/media/audiobooks/Seanan McGuire/Wayward Children #3 - Beneath the Sugar Sky',
 '/Volumes/media/audiobooks/Seanan McGuire/Sparrow Hill Road',
 '/Volumes/media/audiobooks/Seanan McGuire/Boneyard',
 '/Volumes/media/audiobooks/Seanan McGuire/October Daye #2 - A Local Habitation',
 '/Volumes/media/audiobooks/Seanan McGuire/October Daye #1 - Rosemary and Rue',
 '/Volumes/media/audiobooks/Seanan McGuire/October Daye #4 - Late Eclipses',
 '/Volumes/media/audiobooks/Seanan McGuire/Wayward Children #2 - Down Amoung the Sticks and Bones',
 '/Volumes/media/audiobooks/Seanan McGuire/October Daye #6 - Ashes of Honor',
 '/Volumes/media/audiobooks/Helen Harper/Spirit Witch',
 '/Volumes/media/audiobooks/Helen Harper/Slouch Witch',
 '/Volumes/media/audiobooks/Helen Harper/Blood Destiny #1 - Bloodfire',
 '/Volumes/media/audiobooks/Helen Harper/Blood Destiny #2 - Bloodmagic',
 '/Volumes/media/audiobooks/Helen Harper/Star Witch',
 '/Volumes/media/audiobooks/Helen Harper/Highland Magic #1 - Gifted Thief',
 '/Volumes/media/audiobooks/Helen Harper/Blood Destiny #3 - Bloodrage',
 '/Volumes/media/audiobooks/M. C. Beaton/Miss Tonks Turns to Crime',
 '/Volumes/media/audiobooks/M. C. Beaton/Lady Fortescue Steps Out',
 '/Volumes/media/audiobooks/Baroness Emma Orczy/The Scarlet Pimpernel',
 '/Volumes/media/audiobooks/Veronica Henry/How to Find Love in a Bookshop',
 '/Volumes/media/audiobooks/Patricia Briggs/Mercy Thompson #8.5 - Shifting Shadows',
 '/Volumes/media/audiobooks/Patricia Briggs/Mercy Thompson #3 - Iron Kissed',
 '/Volumes/media/audiobooks/Patricia Briggs/Mercy Thompson #6 - River Marked',
 '/Volumes/media/audiobooks/Patricia Briggs/Mercy Thompson #1 - Moon Called',
 '/Volumes/media/audiobooks/Patricia Briggs/Mercy Thompson #9 - Fire Touched',
 '/Volumes/media/audiobooks/Patricia Briggs/Alpha & Omega #3 - Fair Game',
 '/Volumes/media/audiobooks/Patricia Briggs/Mercy Thompson #5 - Silver Bourne',
 '/Volumes/media/audiobooks/Patricia Briggs/Alpha & Omega #1 - Cry Wolf',
 '/Volumes/media/audiobooks/Patricia Briggs/Mercy Thompson #7 - Frost Burned',
 '/Volumes/media/audiobooks/Patricia Briggs/Mercy Thompson #8 - Night Broken',
 '/Volumes/media/audiobooks/Patricia Briggs/Mercy Thompson #4 - Bone Crossed',
 '/Volumes/media/audiobooks/Patricia Briggs/Mercy Thompson #10 - Silence Fallen',
 '/Volumes/media/audiobooks/Patricia Briggs/Alpha & Omega #2 - Hunting Ground',
 '/Volumes/media/audiobooks/Patricia Briggs/Alpha & Omega',
 '/Volumes/media/audiobooks/Patricia Briggs/Alpha & Omega #4 - Dead Heat',
 '/Volumes/media/audiobooks/Patricia Briggs/Alpha & Omega #5 - Burn Bright',
 '/Volumes/media/audiobooks/Patricia Briggs/Mercy Thompson #2 - Blood Bound',
 '/Volumes/media/audiobooks/John Scalzi/John Scalzi - Interdependency 01 - The Collapsing Empire',
 '/Volumes/media/audiobooks/John Scalzi/The Human Division',
 '/Volumes/media/audiobooks/John Scalzi/John Scalzi - Miniatures The Very Short Fiction of John Scalzi',
 '/Volumes/media/audiobooks/John Scalzi/John Scalzi - Fuzzy Nation',
 '/Volumes/media/audiobooks/John Scalzi/John Scalzi - The Androids Dream',
 '/Volumes/media/audiobooks/John Scalzi/John Scalzi - Agent to the Stars',
 '/Volumes/media/audiobooks/John Scalzi/The Last Colony',
 '/Volumes/media/audiobooks/John Scalzi/John Scalzi - Lock In Amber Benson',
 '/Volumes/media/audiobooks/Neil Gaiman/The Ocean at the End of the Lane',
 '/Volumes/media/audiobooks/Neil Gaiman/American Gods',
 '/Volumes/media/audiobooks/Neil Gaiman/Anansi Boys',
 '/Volumes/media/audiobooks/Eloisa James/A Kiss at Midnight',
 '/Volumes/media/audiobooks/Eloisa James/Once Upon a Tower',
 '/Volumes/media/audiobooks/Eloisa James/Three Weeks With Lady X',
 '/Volumes/media/audiobooks/Eloisa James/Four Nights with the Duke',
 '/Volumes/media/audiobooks/Eloisa James/Seven Minutes in Heaven',
 '/Volumes/media/audiobooks/Eloisa James/When Beauty Tamed the Beast',
 '/Volumes/media/audiobooks/Eloisa James/When the Duke Returns',
 '/Volumes/media/audiobooks/Margaret Rogerson/An Enchantment of Ravens',
 '/Volumes/media/audiobooks/Sherry Thomas/The Immortal Heights',
 '/Volumes/media/audiobooks/Sherry Thomas/The Burning Sky',
 '/Volumes/media/audiobooks/Sherry Thomas/A Study in Scarlet Women',
 '/Volumes/media/audiobooks/Sherry Thomas/The Perilous Sea',
 '/Volumes/media/audiobooks/Sherry Thomas/A Conspiracy in Belgravia',
 '/Volumes/media/audiobooks/Christopher Moore/Practical Demonkeeping',
 '/Volumes/media/audiobooks/Christopher Moore/Fluke',
 '/Volumes/media/audiobooks/Christopher Moore/Lamb',
 '/Volumes/media/audiobooks/Christopher Moore/Secondhand Souls',
 '/Volumes/media/audiobooks/Christopher Moore/Fool',
 '/Volumes/media/audiobooks/Christopher Moore/Island of the Sequined Love Nun',
 '/Volumes/media/audiobooks/Christopher Moore/The Lust Lizard of Melancholy Cove',
 '/Volumes/media/audiobooks/Mary Robinette Kowal',
 '/Volumes/media/audiobooks/Gail Carriger/Custard Protocal 2 - Imprudence',
 '/Volumes/media/audiobooks/Gail Carriger/Custard Protocal 1 - Prudence',
 '/Volumes/media/audiobooks/Gail Carriger/Parasol Protectorate 2 - Changeless',
 '/Volumes/media/audiobooks/Gail Carriger/Parasol Protectorate 4 - Heartless',
 '/Volumes/media/audiobooks/Gail Carriger/Parasol Protectorate 3 - Blameless',
 '/Volumes/media/audiobooks/Gail Carriger/Finishing School 1 - Etiquette & Espionage',
 '/Volumes/media/audiobooks/Gail Carriger/Finishing School 3 - Waistcoats & Weaponry',
 '/Volumes/media/audiobooks/Gail Carriger/Finishing School 4 - Manners & Mutiny',
 '/Volumes/media/audiobooks/Gail Carriger/Parasol Protectorate 5 - Timeless',
 '/Volumes/media/audiobooks/Gail Carriger/Finishing School 2 - Curtsies & Conspiracies',
 '/Volumes/media/audiobooks/Gail Carriger/Parasol Protectorate 1 - Soulless',
 '/Volumes/media/audiobooks/Kerstin Gier/Dream On',
 '/Volumes/media/audiobooks/Kerstin Gier/Dream a Little Dream',
 '/Volumes/media/audiobooks/Kerstin Gier/Just Dreaming',
 '/Volumes/media/audiobooks/Tessa Dare/Do You Want to Start a Scandal',
 '/Volumes/media/audiobooks/Tessa Dare/Say Yes to the Marquess',
 '/Volumes/media/audiobooks/Tessa Dare/A Week to be Wicked',
 '/Volumes/media/audiobooks/Tessa Dare/Romancing the Duke',
 '/Volumes/media/audiobooks/Tessa Dare/Any Duchess Will Do',
 '/Volumes/media/audiobooks/Tessa Dare/The Governess Game',
 '/Volumes/media/audiobooks/Tessa Dare/The Duchess Deal',
 '/Volumes/media/audiobooks/Tessa Dare/Lord Dashwood Missed Out',
 '/Volumes/media/audiobooks/Tessa Dare/A Lady by Midnight',
 '/Volumes/media/audiobooks/Tessa Dare/A Night to Surrender',
 '/Volumes/media/audiobooks/Tessa Dare/When a Scot Ties the Knot',
 '/Volumes/media/audiobooks/Juliet Blackwell/Secondhand Spirits',
 '/Volumes/media/audiobooks/Naomi Novik/Throne of Jade',
 '/Volumes/media/audiobooks/Naomi Novik/Victory of Eagles',
 "/Volumes/media/audiobooks/Naomi Novik/His Majesty's Dragon",
 '/Volumes/media/audiobooks/Naomi Novik/Empire of Ivory',
 '/Volumes/media/audiobooks/Naomi Novik/Blood of Tyrants',
 '/Volumes/media/audiobooks/Naomi Novik/Uprooted',
 '/Volumes/media/audiobooks/Melinda Salisbury/The Sleeping Prince',
 "/Volumes/media/audiobooks/Melinda Salisbury/The Sin Eater's Daughter",
 '/Volumes/media/audiobooks/Ally Carter/Take the Key and Lock Her Up',
 '/Volumes/media/audiobooks/Ally Carter/All Fall Down',
 '/Volumes/media/audiobooks/Ally Carter/Not If I Save You First',
 '/Volumes/media/audiobooks/Ally Carter/See How They Run',
 '/Volumes/media/audiobooks/Helen Fielding/Bridget Jones - Mad About the Boy',
 '/Volumes/media/audiobooks/Helen Fielding/Bridget Jones  The Edge of Reason',
 "/Volumes/media/audiobooks/Helen Fielding/Bridget Jones's Baby",
 '/Volumes/media/audiobooks/Douglas Adams/Life, the Universe and Everything',
 '/Volumes/media/audiobooks/Douglas Adams/Dirk Gently',
 "/Volumes/media/audiobooks/Douglas Adams/Hitchhiker's Guide",
 "/Volumes/media/audiobooks/Douglas Adams/Dirk Gently's Holistic Detective Agency",
 '/Volumes/media/audiobooks/Charlotte Brontë/Jane Eyre',
 '/Volumes/media/audiobooks/Cathy Maxwell/The Bride Says No',
 '/Volumes/media/audiobooks/Suzanne Collins/Catching Fire',
 '/Volumes/media/audiobooks/Suzanne Collins/Mockingjay',
 '/Volumes/media/audiobooks/Suzanne Collins/Hunger Games',
 '/Volumes/media/audiobooks/Dakota Cassidy/The Accidental Werewolf',
 '/Volumes/media/audiobooks/Noelle Stevenson/Nimona',
 '/Volumes/media/audiobooks/Maya Banks/In Bed with a Highlander',
 '/Volumes/media/audiobooks/Maya Banks/Sweet Temptation',
 '/Volumes/media/audiobooks/Maya Banks/Seduction of a Highland Lass',
 '/Volumes/media/audiobooks/Maya Banks/Seducing Simon',
 '/Volumes/media/audiobooks/Sarah MacLean/Love By Numbers 1 - Nine Rules to Break When Romancing a Rake',
 '/Volumes/media/audiobooks/Sarah MacLean/Rules Of Scoundrels 1 - A Rogue By Any Other Name',
 '/Volumes/media/audiobooks/Sarah MacLean/Rules Of Scoundrels 2 - One Good Earl Deserves a Lover',
 '/Volumes/media/audiobooks/Sarah MacLean/Scandal & Scoundrel 3 - The Day of the Duchess',
 '/Volumes/media/audiobooks/Sarah MacLean/Love By Numbers 2 - Ten Ways to Be Adored When Landing a Lord',
 '/Volumes/media/audiobooks/Sarah MacLean/Scandal & Scoundrel 1 - The Rogue Not Taken',
 '/Volumes/media/audiobooks/Sarah MacLean/Rules Of Scoundrels 4 - Never Judge a Lady by Her Cover',
 '/Volumes/media/audiobooks/Sarah MacLean/Rules Of Scoundrels 3 - No Good Duke Goes Unpunished',
 "/Volumes/media/audiobooks/Sarah MacLean/Love By Numbers 3 - Eleven Scandals to Start to Win a Duke's Hear",
 '/Volumes/media/audiobooks/Sarah MacLean/Scandal & Scoundrel 2 - A Scot in the Dark',
 '/Volumes/media/audiobooks/Beverly Jenkins/Tempest',
 '/Volumes/media/audiobooks/Jane Austen/Jane Austen - Emma [audiobook]',
 '/Volumes/media/audiobooks/Jane Austen/Mansfield Park',
 '/Volumes/media/audiobooks/Jane Austen/Pride and Prejudice',
 '/Volumes/media/audiobooks/Jane Austen/NMR - Jane Austen - Mansfield Park - Jane Austen - Mansfield Park',
 '/Volumes/media/audiobooks/Jane Austen/Persuation',
 "/Volumes/media/audiobooks/Mackenzi Lee/The Gentleman's Guide to Vice and Virtue",
]