failed updates = (

{'failures': [PosixPath('/Volumes/mangomedia/audiobook_processing/new/Helen Harper/Midnight Smoke'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Rebecca Serle/In Five Years'),
  PosixPath("/Volumes/mangomedia/audiobook_processing/new/Paraic O'Donnell/The House on Vesper Sands"),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Nnedi Okorafor/Remote Control'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Tim Dorsey/Atomic Lobster'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Octavia E. Butler/Wild Seed'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Cindy Spencer Pape/Ether & Elephants'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Mohsin Hamid/Exit West'),
  PosixPath("/Volumes/mangomedia/audiobook_processing/new/Manda Collins/A Lady's Guide to Mischief and Mayhem"),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Cassandra Khaw/Food of the Gods'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Isabel Allende/The Stories of Eva Luna'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Dakota Brown/Becoming'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Ruby Dixon/Slices of Life'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Felicia Grossman/Dalliances & Devotion'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Jennifer Ashley/Scandal and the Duchess'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Bill Pronzini and Marcia Muller/The Bughouse Affair'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Selena Montgomery/Reckless'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Lisa See/The Tea Girl of Hummingbird Lane'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Emma Straub/All Adults Here'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Bethany Bennett/Any Rogue Will Do'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Selena Montgomery/Secrets and Lies'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Marcie R. Rendon/Murder on the Red River'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Selena Montgomery/Hidden Sins'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Christopher Moore/The Serpent of Venice'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Emma Rous/The Perfect Guests'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Brandon Sanderson/Redemption'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Négar Djavadi/Disoriental'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Lynsay Sands/Highland Treasure'),
  PosixPath("/Volumes/mangomedia/audiobook_processing/new/C. M. Waggoner/The Ruthless Lady's Guide to Wizardry"),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Mary Balogh/Only a Promise'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Marlon James/Black Leopard, Red Wolf'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Sophie Sullivan/Ten Rules for Faking It'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Dianne Duvall/The Segonian'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Eden Royce/Root Magic'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Elizabeth Strout/Olive Kitteridge'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Bec McMaster/Dukes Are Forever'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Jim Butcher/Shadowed Souls'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Selena Montgomery/Deception'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Matt Haig/How to Stop Time'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Elizabeth Bear/Range Of Ghosts'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/Namina Forna/The Gilded Ones'),
  PosixPath('/Volumes/mangomedia/audiobook_processing/new/M.A. Carrick/The Mask of Mirrors')],
 'successes': []},
 
 

)